version: '3'

networks:
  jenkins:
    external: true

services:
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    restart: unless-stopped
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

  jenkins-network-creator:
    image: alpine
    container_name: jenkins-network-creator
    networks:
      - jenkins
    command: sh -c "sleep 10 && docker network create jenkins"

  jenkins-blueocean:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-blueocean-test
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"

# networks:
#   jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
